#aws-secret.yaml

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: chat-app
spec: 
  provider: aws
  parameters:
    objects: |
      - objectName: "dev/dashboard/mongo"
        objectType: "secretsmanager"
        jmesPath: 
          - path: "username"
            objectAlias: "MONGO_INITDB_ROOT_USERNAME"  
          - path: "password" 
            objectAlias: "MONGO_INITDB_ROOT_PASSWORD"
          - path: "jwt_key" 
            objectAlias: "JWT_SECRET"  
          - path: "MONGODB_URI"
            objectAlias: "MONGODB_URI"   
  secretObjects:
    - secretName: chatapp-secret
      type: Opaque
      data:
        - objectName: "MONGODB_URI"
          key: MONGODB_URI
        - objectName: "JWT_SECRET" 
          key: jwt
        - objectName: "MONGO_INITDB_ROOT_USERNAME"  #must match with object alias
          key: MONGO_INITDB_ROOT_USERNAME
        - objectName: "MONGO_INITDB_ROOT_PASSWORD"
          key: MONGO_INITDB_ROOT_PASSWORD           



# create jwt secret key on power shell and store on aws secret manager
# [Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Maximum 256 }))
# this is my secret key which i store on aws secret manager-      RtWvZlg8cIZxEluBW/PvT62q9jSPNLxr27CY3QcqxY8=
#"jwt_key":"RtWvZlg8cIZxEluBW/PvT62q9jSPNLxr27CY3QcqxY8="}
# "username":"mongoadmin"
# "password":"secret"
#"MONGODB_URI":"mongodb://mongoadmin:secret@mongodb:27017/chatApp?authSource=admin"
#

#   kubectl get secret chatapp-secret -n chat-app
# kubectl get pods -n chat-app
# kubectl logs -f deployment/backend-deployment -n chat-app
# kubectl exec -it <pod-name> -n chat-app -- printenv | grep MONGODB_URI
# kubectl exec -it <pod-name> -n chat-app -- printenv | grep JWT_SECRET